### --- Extract PR from OR data --- ###
#   OR_data - data generated by function get_ORs_for_draw
#   SNP results (contains relevant q-values and F-values for outlier analyses)
#   ld_test_th - LD threshold defining true positive (in LD-decay units, rho)
#   d_test_th - distance threshold defining true positive (in LD-decay units, rho)
#   p_Va_th - Threshold for defining true positive focal QTn
###



get_PR <- function(draw_ORs,
                   map_filt) {


  true <- unique(map_filt[p_Va > p_Va_th, focal_QTN])

  rbindlist(parallel_apply(draw_ORs,function(ORs){

    if (length(ORs) > 0) {

      #map_filt[marker %in% unlist(ORs)]
      # Identify focal per OR
      OR_focals <- vapply(ORs, function(or) {

        sub <- map_filt[marker %in% or]

        if (nrow(sub) == 0L) return(NA_character_)

        sub[which.max(rho_ld), focal_QTN]

      }, character(1))

      OR_focals <- unique(na.omit(OR_focals))

      # Confusion components
      TP <- sum(OR_focals %in% true)
      FP <- length(ORs) - TP
      FN <- length(setdiff(true, OR_focals))

      precision <- if ((TP + FP) > 0) TP / (TP + FP) else 0
      recall    <- if ((TP + FN) > 0) TP / (TP + FN) else 0
      PR        <- precision * recall

      # Neutral FP check (vectorized)
      neutral_markers <- unique(map[Chr_type == "ntrl", marker])

      FP_ntrl <- sum(vapply(ORs, function(or) {
        any(or %in% neutral_markers)
      }, logical(1)))

      return(data.table(
        TP = TP,
        FP = FP,
        FN = FN,
        precision = precision,
        recall = recall,
        PR = PR,
        FP_ntrl = FP_ntrl,
        OR_focals = list(list(OR_focals))
      ))

    } else {

      return(data.table(
        TP = 0,
        FP = 0,
        FN = length(true),
        precision = 0,
        recall = 0,
        PR = 0,
        FP_ntrl = 0,
        OR_focals = list(list(character()))
      ))
    }
  },cores=cores))


}

### ---  Get oulier regions from C-scores --- ###
#   rho_ld_lim - ld threshold for defining ORs
#   rho_d_lim - d threshold for defining ORs
#   tau_C_lim - C-threshold for defining outlier SNPs
#   n_rep - number of draws
###

get_ORs_from_C <- function(GTs,
                           map,
                           C_vals,
                           decay_tbl,
                           rho_ld_lim = list(min = 0.5, max = 1.0),
                           rho_d_lim  = list(min = 0.90, max = 1.0),
                           tau_C_lim  = list(min = 1e-6, max = 0.5),
                           n_cores    = 1,
                           n_rep      = 500) {

  ## ---- create GDS ----
  gds_path <- tempfile(fileext = ".gds")
  gds <- create_gds_from_geno(geno = GTs, map = map, gds_path)
  on.exit({ snpgdsClose(gds); unlink(gds_path) }, add = TRUE)

  ids <- read_gds_ids(gds)
  C_vals <- as.matrix(C_vals)
  methods <- colnames(C_vals)

  ## ---- restrict to SNPs with any signal ----
  keep <- apply(C_vals, 1, max) > 0
  snps_keep <- ids$snp_id[keep]
  idx_keep  <- which(keep)

  if (length(idx_keep) == 0) {
    return(data.table())
  }

  ## ---- build LD edge lists per chromosome ----
  el_chr <- rbindlist(lapply(unique(ids$snp_chr[idx_keep]), function(ch) {
    idx <- idx_keep[ids$snp_chr[idx_keep] == ch]
    get_el(gds, idx = idx, slide_win_ld = -1, n_cores = n_cores)
  }))

  ## ---- OR draws ----
  out <- vector("list", n_rep)

  for (r in seq_len(n_rep)) {

    tau_C  <- runif(1, tau_C_lim$min,  tau_C_lim$max)
    rho_ld <- runif(1, rho_ld_lim$min, rho_ld_lim$max)
    rho_d  <- runif(1, rho_d_lim$min,  rho_d_lim$max)

    ## thresholds per chromosome
    d_th_by_chr <- setNames(
      d_from_rho(decay_tbl$summary$a, rho_d),
      decay_tbl$summary$Chr
    )

    ld_th_by_chr <- setNames(
      decay_tbl$summary$b + (1 - decay_tbl$summary$b) * (1 - rho_ld),
      decay_tbl$summary$Chr
    )

    el_chr[, d_th  := d_th_by_chr[Chr1]]
    el_chr[, ld_th := ld_th_by_chr[Chr1]]

    mean_d_th  <- mean(el_chr$d_th,  na.rm = TRUE)
    mean_ld_th <- mean(el_chr$ld_th, na.rm = TRUE)

    ## ---- per-method ORs ----
    out[[r]] <- rbindlist(lapply(seq_along(methods), function(i) {

      me <- methods[i]
      outl_me <- ids$snp_id[C_vals[, i] > tau_C]

      ed <- el_chr[
        r2 > ld_th & d < d_th &
          SNP1 %in% outl_me & SNP2 %in% outl_me,
        .(SNP1, SNP2)
      ]

      if (nrow(ed) == 0L) {
        ors <- list()
      } else {
        g <- igraph::graph_from_data_frame(ed, directed = FALSE)
        comps <- igraph::components(g)
        ors <- split(names(comps$membership), comps$membership)
        names(ors) <- seq_along(ors)
      }

      data.table(
        method = me,
        tau_C  = tau_C,
        rho_d  = rho_d,
        rho_ld = rho_ld,
        mean_d_th_OR  = mean_d_th,
        mean_ld_th_OR = mean_ld_th,
        ORs = list(ors)
      )
    }))
  }
  rbindlist(out)
}
