#' Plot method for LDscn_pipeline objects
#'
#' Provides high-level visualization for results generated by
#' `LDscn_pipeline()`. Available plot types:
#'
#' \itemize{
#'   \item \code{"manhattan"}: Manhattan-style genome scan plot.
#'   \item \code{"qq"}: QQ plot of LD-scaled statistics.
#'   \item \code{"decay"}: LD structure with fitted decay curve.
#' }
#'
#' @param x An object of class `"LDscn_pipeline"`.
#' @param type Character. One of `"manhattan"`, `"qq"`, or `"decay"`.
#' @param ... Additional arguments passed to the underlying plotting function.
#'
#' @return A ggplot or patchwork object (or base plot for `"decay"`).
#' @export
plot.LDscn_pipeline <- function(x,
                                type = c("manhattan", "qq", "decay"),
                                ...) {

  type <- match.arg(type)

  if (!inherits(x, "LDscn"))
    stop("x must be an LDscn_pipeline object.")

  switch(
    type,

    manhattan = {
      plot_ldscn_manhattan(x, ...)
    },

    qq = {
      if (is.null(x$scan))
        stop("Scan results not found in object.")
      plot(x$scan, ...)
    },

    decay = {
      if (is.null(x$ld_str) || is.null(x$decay))
        stop("LD structure or decay not stored in object.")
      plot_ld_decay(x, ...)
    }
  )
}
